In [40]:
import pandas as pd
import sklearn
from sklearn.preprocessing import LabelEncoder

In [83]:
train=pd.read_csv('Train/Train.csv')
test=pd.read_csv('Test/Test.csv')

In [85]:
not_useful=['name','ticket','cabin','embarked','boat','body','home.dest']
Train_clean=train.drop(columns=not_useful)
Test_clean=test.drop(columns=not_useful)

In [88]:
Train_clean=Train_clean.fillna(Train_clean['age'].mean())
Test_clean=Test_clean.fillna(Test_clean['age'].mean())
le=LabelEncoder()

In [89]:
Train_clean['sex']=le.fit_transform(Train_clean['sex'])
Test_clean['sex']=le.fit_transform(Test_clean['sex'])

In [90]:
Train_clean

      pclass  survived  sex        age  sibsp  parch      fare
0        3.0       0.0    0  29.838978    0.0    0.0    7.7500
1        2.0       0.0    1  39.000000    0.0    0.0   26.0000
2        2.0       1.0    0  40.000000    0.0    0.0   13.0000
3        3.0       1.0    0  31.000000    1.0    1.0   20.5250
4        3.0       1.0    0  29.838978    2.0    0.0   23.2500
5        2.0       0.0    1  16.000000    0.0    0.0   26.0000
6        2.0       0.0    1  43.000000    0.0    1.0   21.0000
7        1.0       1.0    0  49.000000    0.0    0.0   25.9292
8        1.0       0.0    1  48.000000    0.0    0.0   50.4958
9        2.0       0.0    1  29.838978    0.0    0.0   12.8750
10       2.0       0.0    1  21.000000    2.0    0.0   73.5000
11       3.0       1.0    0  29.838978    0.0    0.0    7.8292
12       2.0       1.0    0  48.000000    0.0    2.0   36.7500
13       2.0       1.0    1   8.000000    1.0    1.0   36.7500
14       3.0       0.0    1  22.000000    0.0    0.0    7.8958
15       1.0       0.0    1  29.838978    0.0    0.0   35.0000
16       1.0       1.0    0  39.000000    1.0    1.0  110.8833
17       3.0       0.0    0  30.500000    0.0    0.0    7.7500
18       2.0       0.0    1  29.838978    0.0    0.0   15.0500
19       3.0       0.0    1  16.000000    2.0    0.0   18.0000
20       1.0       1.0    0  55.000000    2.0    0.0   25.7000
21       1.0       1.0    1  80.000000    0.0    0.0   30.0000
22       2.0       1.0    0  17.000000    0.0    0.0   12.0000
23       2.0       1.0    0  28.000000    0.0    0.0   13.0000
24       3.0       0.0    1  21.000000    0.0    0.0    7.8958
25       2.0       0.0    1  52.000000    0.0    0.0   13.5000
26       3.0       1.0    1  21.000000    0.0    0.0    7.7750
27       1.0       0.0    1  47.000000    0.0    0.0   42.4000
28       3.0       0.0    0   9.000000    2.0    2.0   34.3750
29       3.0       0.0    1   8.000000    4.0    1.0   29.1250
...      ...       ...  ...        ...    ...    ...       ...
979      3.0       0.0    1  36.000000    1.0    0.0   15.5500
980      3.0       0.0    1  21.000000    0.0    0.0    7.2250
981      3.0       1.0    0  27.000000    0.0    1.0   12.4750
982      2.0       0.0    1  36.000000    0.0    0.0   13.0000
983      3.0       0.0    1  21.000000    2.0    0.0   24.1500
984      2.0       1.0    0  34.000000    0.0    0.0   13.0000
985      1.0       1.0    0  55.000000    0.0    0.0   27.7208
986      3.0       1.0    1  29.838978    1.0    1.0   22.3583
987      1.0       1.0    0  39.000000    1.0    0.0   55.9000
988      3.0       0.0    1  24.000000    0.0    0.0    7.8958
989      3.0       0.0    0  29.838978    0.0    0.0    7.7500
990      3.0       1.0    1  20.000000    0.0    0.0    7.9250
991      1.0       1.0    0  33.000000    1.0    0.0   90.0000
992      3.0       1.0    0  29.838978    0.0    0.0    7.7500
993      1.0       1.0    0  45.000000    1.0    0.0   52.5542
994      3.0       1.0    0  23.000000    0.0    0.0    8.0500
995      2.0       1.0    1   1.000000    0.0    2.0   37.0042
996      3.0       0.0    1  34.500000    0.0    0.0    7.8292
997      3.0       0.0    1  32.000000    0.0    0.0   22.5250
998      2.0       1.0    0  19.000000    0.0    0.0   13.0000
999      1.0       1.0    0  35.000000    0.0    0.0  135.6333
1000     3.0       0.0    0  28.000000    1.0    1.0   14.4000
1001     2.0       0.0    1  40.000000    0.0    0.0   16.0000
1002     1.0       1.0    0  22.000000    0.0    1.0   55.0000
1003     3.0       0.0    1  25.000000    0.0    0.0    7.0500
1004     1.0       1.0    1  40.000000    0.0    0.0   31.0000
1005     3.0       0.0    0  37.000000    0.0    0.0    9.5875
1006     1.0       1.0    0  23.000000    1.0    0.0  113.2750
1007     3.0       1.0    1  12.000000    1.0    0.0   11.2417
1008     3.0       0.0    1  30.000000    0.0    0.0    8.0500

[1009 rows x 7 columns]

In [91]:
#Define Entropy and information Gain
def Entropy(col):
    N=col.shape[0]
    ent=0.0
    Y=np.unique(col,return_counts=True)
    for i in Y[1]:
        p=i/N
        ent+=-(p*np.log2(p))
    return ent

In [92]:
def split_data(x_data,f_key,f_val):
    x_left=pd.DataFrame([],columns=x_data.columns)#Creates an empty pandas dataframe with given columns
    x_right=pd.DataFrame([],columns=x_data.columns)
    for j in range(x_data.shape[0]):
        val=x_data[f_key].loc[j]
        if val<f_val:
            x_left=x_left.append(x_data.loc[j])
        else:
            x_right=x_right.append(x_data.loc[j])
    return x_left,x_right

In [93]:
def Info_gain(x_data,f_key,f_val):
    left,right=split_data(x_data,f_key,f_val)
    l=float(left.shape[0]/x_data.shape[0])
    r=float(right.shape[0]/x_data.shape[0])
    sum = Entropy(Train_clean['survived'])-(l*Entropy(left['survived'])+r*Entropy(right['survived']))
    return sum

In [94]:
L=[]
features=['pclass','sex','age','sibsp','parch','fare']
for i in features:
    val=Info_gain(Train_clean,i,Train_clean[i].mean())
    L.append(val)
    print(features[np.argmax(L)])

pclass
sex
sex
sex
sex
sex

In [95]:
#Creating a decision tree
class Decision_tree:
    def __init__(self,depth=0,max_depth=3):
        self.left=None
        self.right=None
        self.f_key=None
        self.f_val=None
        self.depth=depth
        self.max_depth=max_depth
        self.target=None
    def train(self,X_Train):
    
        features=['pclass','sex','age','sibsp','parch','fare']
        L=[]
        for i in features:
            val=Info_gain(X_Train,i,X_Train[i].mean())
            L.append(val)
        self.f_key=features[np.argmax(L)]
        self.f_val=X_Train[self.f_key].mean()
        print('Making Features in',self.f_key)
        data_left,data_right=split_data(X_Train,self.f_key,self.f_val)
        data_left=data_left.reset_index(drop=True)
        data_right=data_right.reset_index(drop=True)
            #Base Case --->when a leaf node occurs
        if data_left.shape[0]==0 or data_right.shape[0]==0:
            if X_Train.survived.mean()>=0.5:
                self.target=1
            else:
                self.target=0
            return
            #Base Case ---->when max_depth reached
        if(self.depth>=self.max_depth):
            if X_Train.survived.mean() >= 0.5:
                self.target=1
            else:
                self.target=0
            return
            #Recursive case
            #left-Tree
        self.left=Decision_tree(depth=self.depth+1,max_depth=self.max_depth)
        print('left')
        self.left.train(data_left)
            #Right-Tree
        self.right=Decision_tree(depth=self.depth+1,max_depth=self.max_depth)
        print('right')
        self.right.train(data_right)
            #Set Target After Every Node
        if(self.depth>=self.max_depth):
            if X_Train.survived.mean() >=0.5:
                self.target=1
            else:
                self.target=0
            return
    def Traverse_Tree(self,test):
        if test[self.f_key]>self.f_val:
                #Go to right
            
                #else if right side is not present we will return target
            if self.right is None:
                return self.target
                
            return self.right.Traverse_Tree(test)
        else:
            if self.left is None:
                return self.target
            return self.left.Traverse_Tree(test)

In [81]:
d=Decision_tree()

In [82]:
d.train(Train_clean)

Making Features in sex
left
Making Features in pclass
left
Making Features in pclass
left
Making Features in fare
right
Making Features in parch
right
Making Features in parch
left
Making Features in sibsp
right
Making Features in fare
right
Making Features in fare
left
Making Features in parch
left
Making Features in age
right
Making Features in age
right
Making Features in pclass
left
Making Features in age
right
Making Features in sibsp

In [196]:
y_pred=[]
for ix in range(Test_clean.shape[0]):
    val=d.Traverse_Tree(Test_clean.loc[ix])
    y_pred.append(val)

In [197]:
y_pred=np.array(y_pred)

In [198]:
y_pred.shape

(300,)

In [199]:
sample=pd.read_csv('Test/sample_submission.csv')

In [200]:
sample

      Id  survived
0      0       1.0
1      1       1.0
2      2       1.0
3      3       1.0
4      4       1.0
5      5       1.0
6      6       1.0
7      7       1.0
8      8       1.0
9      9       1.0
10    10       1.0
11    11       1.0
12    12       1.0
13    13       1.0
14    14       1.0
15    15       1.0
16    16       1.0
17    17       1.0
18    18       1.0
19    19       1.0
20    20       1.0
21    21       1.0
22    22       1.0
23    23       1.0
24    24       1.0
25    25       1.0
26    26       1.0
27    27       1.0
28    28       1.0
29    29       1.0
..   ...       ...
270  270       1.0
271  271       1.0
272  272       1.0
273  273       1.0
274  274       1.0
275  275       1.0
276  276       1.0
277  277       1.0
278  278       1.0
279  279       1.0
280  280       1.0
281  281       1.0
282  282       1.0
283  283       1.0
284  284       1.0
285  285       1.0
286  286       1.0
287  287       1.0
288  288       1.0
289  289       1.0
290  290       1.0
291  291       1.0
292  292       1.0
293  293       1.0
294  294       1.0
295  295       1.0
296  296       1.0
297  297       1.0
298  298       1.0
299  299       1.0

[300 rows x 2 columns]

In [250]:
y_pred_id=np.zeros((y_pred.shape[0],1))

In [251]:
for i in range(y_pred.shape[0]):
    y_pred_id[i]+=i

In [252]:
y_pred=y_pred.reshape((-1,1))

In [253]:
y_pred=np.hstack((y_pred_id,y_pred))

In [254]:
y_pred[0]=0
name=np.array(['Id','survived']).reshape((1,-1))
name

array([['Id', 'survived']], dtype='<U8')

In [255]:
#y_pred=np.vstack((name,y_pred))

In [256]:
np.savetxt('foo.csv',y_pred,delimiter=',')

In [257]:
y_pred.shape

(300, 2)

In [211]:
from sklearn.tree import DecisionTreeClassifier

In [213]:
X_Train=Train_clean.drop(columns='survived')

In [214]:
Y_Train=Train_clean['survived']

In [216]:
X_Test=Test_clean

In [218]:
sktree=DecisionTreeClassifier?

In [221]:
sktree=DecisionTreeClassifier(criterion='entropy')

In [222]:
sktree.fit(X_Train,Y_Train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [223]:
sktree.predict(X_Test)

array([1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 1., 1., 1., 0., 1., 0., 1.,
       0., 1., 1., 0., 1., 1., 1., 1., 0., 0., 0., 0., 1., 0., 1., 0., 1.,
       1., 1., 1., 0., 0., 0., 0., 1., 0., 1., 1., 0., 0., 0., 1., 0., 0.,
       0., 1., 1., 0., 0., 0., 1., 0., 1., 1., 0., 0., 1., 0., 0., 1., 0.,
       0., 0., 0., 0., 1., 1., 0., 0., 0., 1., 1., 1., 1., 1., 0., 1., 0.,
       0., 1., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 0., 1., 1., 0., 1., 0., 0., 0., 0., 1., 0., 1., 1., 1., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 1., 0., 1., 0., 0., 0., 0., 1., 1., 1., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 1., 1., 1., 0., 0.,
       0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 0., 1., 0., 1.,
       0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1.,
       0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 1., 0., 1., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 1., 0., 1., 1., 0.,
       0., 0., 1., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 1., 1.,
       0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0.])

In [227]:
sktree.score(X_Test,Y_Train[:300])

0.5366666666666666

In [228]:
from sklearn.ensemble import RandomForestClassifier

In [231]:
rf=RandomForestClassifier?

In [247]:
rf=RandomForestClassifier(n_estimators=22,criterion='entropy',max_depth=5)

In [248]:
rf.fit(X_Train,Y_Train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=5, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=22, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [249]:
y_pred=rf.predict(X_Test)

In [235]:
rf.score(X_Train,Y_Train)

0.8354806739345887